
DECLARE_MODULE_AND_TEMPLATE(PositionModule, PositionModuleTemplate)
DECLARE_MODULE_AND_TEMPLATE(OrientationModule, OrientationModuleTemplate)
DECLARE_MODULE_AND_TEMPLATE(ApparenceModule, ApparenceModuleTemplate)
DECLARE_MODULE_AND_TEMPLATE(CameraMoverModule, CameraMoverModuleTemplate)
DECLARE_MODULE_AND_TEMPLATE(LinkToOwnerModule, LinkToOwnerModuleTemplate)

#include "ECSGameplay_Specific/ModuleList.inl"
