
DECLARE_MODULE_AND_TEMPLATE(PositionModule, PositionModuleTemplate)
DECLARE_MODULE_AND_TEMPLATE(OrientationModule, OrientationModuleTemplate)
DECLARE_MODULE_AND_TEMPLATE(ApparenceModule, ApparenceModuleTemplate)
