
name: compileall

input:
  target:
    description: 'Compilation target'
    required: true
    default: 'Release'

runs:
  using: "composite"
  steps:
    run: py -u Script/Compil/BuildAll.py $INPUT_TARGET msbuild.exe
    shell: bash