
DECLARE_MODULE_AND_TEMPLATE(ColonyModule, ColonyModuleTemplate)
DECLARE_MODULE_AND_TEMPLATE(ResourceStorageModule, ResourceStorageModuleTemplate)
DECLARE_MODULE_AND_TEMPLATE(ResourceProductionModule, ResourceProductionModuleTemplate)
DECLARE_MODULE_AND_TEMPLATE(ResourceHarvesterModule, ResourceHarvesterModuleTemplate)
DECLARE_MODULE_AND_TEMPLATE(ColonyPeonsManagementModule, ColonyPeonsManagementModuleTemplate)
DECLARE_MODULE_AND_TEMPLATE(PeonSpawnModule, PeonSpawnModuleTemplate)