// clang-format off
DECLARE_ENUM(GAMEPAD_AXIS_LEFT_X, 0),
DECLARE_ENUM(GAMEPAD_AXIS_LEFT_Y,1),
DECLARE_ENUM(GAMEPAD_AXIS_RIGHT_X,2),
DECLARE_ENUM(GAMEPAD_AXIS_RIGHT_Y,3),
DECLARE_ENUM(GAMEPAD_AXIS_LEFT_TRIGGER,4),
DECLARE_ENUM(GAMEPAD_AXIS_RIGHT_TRIGGER,5),
DECLARE_ENUM(GAMEPAD_AXIS_LAST,6),
      // clang-format on
