// clang-format off
DECLARE_ENUM(MOUSE_BUTTON_1, 0),
DECLARE_ENUM(MOUSE_BUTTON_2, 1),
DECLARE_ENUM(MOUSE_BUTTON_3, 2),
DECLARE_ENUM(MOUSE_BUTTON_4, 3),
DECLARE_ENUM(MOUSE_BUTTON_5, 4),
DECLARE_ENUM(MOUSE_BUTTON_6, 5),
DECLARE_ENUM(MOUSE_BUTTON_7, 6),
DECLARE_ENUM(MOUSE_BUTTON_8, 7),
DECLARE_ENUM(MOUSE_BUTTON_LAST, 8)
      // clang-format on
