# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-release"
  build-BGFX:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Clone BGFX
        run: py -u Script/Cloning/CloneSubmodules.py -b
        shell: bash

      - name: Build BGFX Release
        run: py -u Script/Compil/BuildAll.py -b -c Release -m msbuild.exe
        shell: bash

      - name: Build BGFX Debug
        run: py -u Script/Compil/BuildAll.py -b -c Debug -m msbuild.exe
        shell: bash

      - name: Upload BGFX release build
        uses: actions/upload-artifact@v2
        with:
          name: BGFX-Binaries-Release
          path: External/BGFX/bgfx/.build/win64_vs2019/bin/*Release.*
          if-no-files-found: error

      - name: Upload BGFX debug build
        uses: actions/upload-artifact@v2
        with:
          name: BGFX-Binaries-Debug
          path: External/BGFX/bgfx/.build/win64_vs2019/bin/*Debug.*
          if-no-files-found: error


  # This workflow contains a single job called "build-release"
  build-release:
    # The type of runner that the job will run on
    runs-on: windows-latest

    needs: build-BGFX
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Clone ENGINE submodules
        run: py -u Script/Cloning/CloneSubmodules.py -e
        shell: bash

      - run: |
          mkdir External/BGFX/bgfx/.build/
          mkdir External/BGFX/bgfx/.build/win64_vs2019/
          mkdir External/BGFX/bgfx/.build/win64_vs2019/bin/

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: BGFX-Binaries-Release
          path: External/BGFX/bgfx/.build/win64_vs2019/bin/

      - name: Build all
        run: py -u Script/Compil/BuildAll.py -e -c Release -m msbuild.exe
        shell: bash

      - name: Upload Release build
        uses: actions/upload-artifact@v2
        with:
          name: ECSEngine-Binaries-Release
          path: |
            bin/Win64/Release/Launcher.exe
            bin/Win64/Release/glfw3.dll
          if-no-files-found: error

      - name: Upload AssetCooker Release build
        uses: actions/upload-artifact@v2
        with:
          name: AssetCooker-Binaries-Release
          path: |
            bin/Win64/Release/AssetCooker.exe
            bin/Win64/Release/glfw3.dll
            bin/Win64/Release/assimp-vc142-mt.dll
          if-no-files-found: error

  # This workflow contains a single job called "build-release"
  build-debug:
    # The type of runner that the job will run on
    runs-on: windows-latest

    needs: build-BGFX

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Clone ENGINE submodules
        run: py -u Script/Cloning/CloneSubmodules.py -e
        shell: bash

      - run: |
          mkdir External/BGFX/bgfx/.build/
          mkdir External/BGFX/bgfx/.build/win64_vs2019/
          mkdir External/BGFX/bgfx/.build/win64_vs2019/bin/

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: BGFX-Binaries-Debug
          path: External/BGFX/bgfx/.build/win64_vs2019/bin/

      - name: Build all
        run: py -u Script/Compil/BuildAll.py -e -c Debug -m msbuild.exe
        shell: bash

# This workflow contains a single job called "build-release"
  build-profile:
    # The type of runner that the job will run on
    runs-on: windows-latest

    needs: build-BGFX

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Clone ENGINE submodules
        run: py -u Script/Cloning/CloneSubmodules.py -e
        shell: bash

      - run: |
          mkdir External/BGFX/bgfx/.build/
          mkdir External/BGFX/bgfx/.build/win64_vs2019/
          mkdir External/BGFX/bgfx/.build/win64_vs2019/bin/

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: BGFX-Binaries-Release
          path: External/BGFX/bgfx/.build/win64_vs2019/bin/

      - name: Build all
        run: py -u Script/Compil/BuildAll.py -e -c Profile -m msbuild.exe
        shell: bash

# This workflow contains a single job called "build-release"
  build-final:
    # The type of runner that the job will run on
    runs-on: windows-latest

    needs: build-BGFX

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Clone ENGINE submodules
        run: py -u Script/Cloning/CloneSubmodules.py -e
        shell: bash

      - run: |
          mkdir External/BGFX/bgfx/.build/
          mkdir External/BGFX/bgfx/.build/win64_vs2019/
          mkdir External/BGFX/bgfx/.build/win64_vs2019/bin/

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: BGFX-Binaries-Release
          path: External/BGFX/bgfx/.build/win64_vs2019/bin/

      - name: Build all
        run: py -u Script/Compil/BuildAll.py -e -c Final -m msbuild.exe
        shell: bash

  generate-assets:
    runs-on: windows-latest
    needs: build-release

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - run: |
          mkdir build/
          mkdir bin/
          mkdir bin/Win64/
          mkdir bin/Win64/Release/

      - name: AssetCooker-Binaries-Release
        uses: actions/download-artifact@v2
        with:
          name: AssetCooker-Binaries-Release
          path: bin/Win64/Release/

      - name: Clone Assets submodules
        run: py -u Script/Cloning/CloneSubmodules.py --assets
        shell: bash

      - name: Run Asset cooking
        run: py -u Script/Generation/GenerateData.py
        shell: bash


  cleanup_job:
    needs: [build-final, build-profile, build-debug, generate-assets]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: call webhook to delete artifacts
      env:
        FOR_WEBHOOKS_SECRET: ${{ secrets.ACCESS_TOKEN }}
      run: |
        echo "::add-mask::$FOR_WEBHOOKS_SECRET"
        curl --verbose --fail --show-error --location --request POST "https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches" --header "Authorization: token $FOR_WEBHOOKS_SECRET" --header 'Content-Type: application/json' --header 'Accept: application/vnd.github.everest-preview+json' --data-raw "{ \"event_type\": \"delete_all_artifacts\", \"client_payload\": {\"parent_runid\": \"$GITHUB_RUN_ID\", \"parent_repo\": \"$GITHUB_REPOSITORY\"} }"